### ISSUE TITLE
Puffin armhf support

### ISSUE THREAD

**Issue by coder0107git** [ZhymabekRoman/Puffin-Browser-on-Linux#1]
Please add armhf support. The latest armhf packge for puffin can be found at [https://download.puffinbrowser.com/linux/raspbian/puffin-internet-terminal-demo-armhf-latest.php](https://download.puffinbrowser.com/linux/raspbian/puffin-internet-terminal-demo-armhf-latest.php)

**Comment by ZhymabekRoman** [comment]
I apologize for taking so long to respond. I wanted to add Puffin builds for armhf a long time ago, but after a test installation I found out that they are adapted only to RaspberyPI, and require some dependencies which are only in RaspberyPI

**Comment by ZhymabekRoman** [comment]
Done! Thanks for reporting!
