### ISSUE TITLE
How did you recompile this for amd64 and i386?

### ISSUE THREAD

**Issue by Botspot** [ZhymabekRoman/Puffin-Browser-on-Linux#2]
I write software for raspberry pi and came across your repo today. How did you manage to compile debs for conventional Linux CPU architectures? Did you start with Puffin's smartphone app?

**Comment by ZhymabekRoman** [comment]
Sorry, I don't quite understand your question. You write apps for raspbery pi, but what does this repository have to do with it? Or are you writing a browser like Puffin?

**Comment by Botspot** [comment]
I'm not writing a browser. I simply came across your repo while researching something else and was intrigued how you made Puffin available for x86 Linux.
AFAIK, Puffin is only available for armhf linux for the Raspberry Pi, so I'm curious how you got it running on i386 and amd64. I'm not aware of Puffin being open source, so how did you make these debs?

**Comment by ZhymabekRoman** [comment]
> I'm not writing a browser. I simply came across your repo while researching something else and was intrigued how you made Puffin available for x86 Linux. AFAIK, Puffin is only available for armhf linux for the Raspberry Pi, so I'm curious how you got it running on i386 and amd64. I'm not aware of Puffin being open source, so how did you make these debs?

Nothing supernatural - builds for i386, amd64 are available in the official Puffin repositories, but the developers themselves haven't written anything about it. Because of this, I created this repository with instructions

**Comment by Botspot** [comment]
> Nothing supernatural - builds for i386, amd64 are available in the official Puffin repositories, but the developers themselves haven't written anything about it.

Thank you - that answers my question. Have a great day.

**Comment by Botspot** [comment]
I just did some checking, and Puffin appears to have an aarch64 release. Can you look at it? Your readme said this was still a work in progress, but I understand that was a year ago.

Here's the URL I found: https://download.puffinbrowser.com/repo/pool/stable/arm64/puffin-internet-terminal-demo_8.2.4.705_arm64.deb

**Comment by ZhymabekRoman** [comment]
> I just did some checking, and Puffin appears to have an aarch64 release. Can you look at it? Your readme said this was still a work in progress, but I understand that was a year ago.

armv7 and aarch64 builds are linked to RaspberyPI libraries, and if install Puffin for example on OrangePI, Android (Termux environment, using proot-distro) and other arm devices Puffin will not work. The source code of RaspberyPI libraries is open, and I think we can make an LD_PRELOAD library, which makes Puffin independent from RaspberyPI libraries. If I had the time, I would do it.

**Comment by Botspot** [comment]
It may also be possible to emulate the x86 binary with an emulator like Box86. I usually wouldn't advise emulating a web browser, but in the case of puffin there may not be much of a performance hit as it's a cloud service browser.
