### ISSUE TITLE
Fontconfig warning

### ISSUE THREAD

**Issue by jidanni** [ZhymabekRoman/Puffin-Browser-on-Linux#3]
Good job!
Only minor errors, here on Debian: same as
https://github.com/faressoft/terminalizer/issues/90

**Comment by ZhymabekRoman** [comment]
Which Linux distribution are you using? And please provide `uname -a` output. Did you have a GPU?

**Comment by jidanni** [comment]
Debian sid
$ uname -a
Linux jidanni5 6.1.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.11-1 (2023-02-09) x86_64 GNU/Linux
\# lshw|grep -ci gpu 
0    #not sure if this is how to test for a GPU.

```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[15820:15841:0213/150918.142338:ERROR:buffer_manager.cc(491)] [.BrowserCompositor-0x2f6105cfe500]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```
But the browser runs OK.

**Comment by ZhymabekRoman** [comment]
I think we can suppress this warning, thanks for creating this issue!
