### ISSUE TITLE
Can't easily shell-complete

### ISSUE THREAD

**Issue by jidanni** [ZhymabekRoman/Puffin-Browser-on-Linux#4]
Actually it is too bad we can't just tab-complete "puffin", due to the two links:
$ puff'<TAB>'
puffin-internet-terminal-demo@ puffin_demo@

**Comment by ZhymabekRoman** [comment]
Hmm, okey, i'll see

**Comment by ZhymabekRoman** [comment]
As a workaround I can recommend you to alias `puffin` command:
```
alias puffin=puffin_demo
```
