### ISSUE TITLE
Options to tweak rendering balance more to upstream

### ISSUE THREAD

**Issue by jidanni** [ZhymabekRoman/Puffin-Browser-on-Linux#6]
Say one has an obsolete hardware with obsolete software that can't be
updated.

Newer (fancy) web pages render terribly on it.

There is a hope: Puffin, that renders remotely, and sends the
results to the hardware.

But alas, puffin also renders poorly, as it too is relying on the
obsolete hardware's obsolete webkit etc.

So maybe there could be a way of telling puffin to do more of the
rendering remotely, and less back on the hardware.

Sort of like telling puffin to assume the hardware is a "dumb
terminal".

**Comment by ZhymabekRoman** [comment]
I don't think it can be implemented, firstly Puffin's source code is closed, so we can't do anything big. As a workaround, I can recommend optimizing your Linux device, e.g. disabling the Spectre and Meldown vulnerability mitigrations (~20% speedup) and setting the maximum priority for the Puffin process using nice (renice) and ionice (or setting the `performance` governor).

Some links:
https://linuxreviews.org/HOWTO_make_Linux_run_blazing_fast_(again)_on_Intel_CPUs
https://ostechnix.com/how-to-make-linux-system-to-run-faster-on-intel-cpus/
https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization
https://stevescargall.com/2020/02/12/how-to-set-linux-cpu-scaling-governor-to-max-performance/
https://www.maketecheasier.com/manage-priority-io-processes-linux/

**Comment by jidanni** [comment]
(I was thinking if there was a puffin --render-even-more-upstream switch that one day worked on linux, then it could even work on old _ipads_ too.)

**Comment by ZhymabekRoman** [comment]
I'll see, maybe there are some ways to optimise it.
